config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :project_categories
  resources :projects

   root 'projects#index'

  
end

app/models/project.rb
class Project < ActiveRecord::Base
has_many :project_categories
 accepts_nested_attributes_for :project_categories, allow_destroy: true

  def questions_for_form
    collection = project_categories.where(project_id: id)
    collection.any? ? collection : project_categories.build
  end
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  belongs_to :project
  has_many :tasks
  accepts_nested_attributes_for :tasks, allow_destroy: true

  def answers_for_form
    collection = tasks.where(project_id: id)
    collection.any? ? collection : tasks.build
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project_category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/project_categories_controller.rb
class ProjectCategoriesController < ApplicationController
  before_action :set_project_category, only: [:show, :edit, :update, :destroy]

  # GET /project_categories
  # GET /project_categories.json
  def index
    @project_categories = ProjectCategory.all
  end

  # GET /project_categories/1
  # GET /project_categories/1.json
  def show
  end

  # GET /project_categories/new
  def new
    @project_category = ProjectCategory.new
  end

  # GET /project_categories/1/edit
  def edit
  end

  # POST /project_categories
  # POST /project_categories.json
  def create
    @project_category = ProjectCategory.new(project_category_params)

    respond_to do |format|
      if @project_category.save
        format.html { redirect_to @project_category, notice: 'Project category was successfully created.' }
        format.json { render :show, status: :created, location: @project_category }
      else
        format.html { render :new }
        format.json { render json: @project_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_categories/1
  # PATCH/PUT /project_categories/1.json
  def update
    respond_to do |format|
      if @project_category.update(project_category_params)
        format.html { redirect_to @project_category, notice: 'Project category was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_category }
      else
        format.html { render :edit }
        format.json { render json: @project_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_categories/1
  # DELETE /project_categories/1.json
  def destroy
    @project_category.destroy
    respond_to do |format|
      format.html { redirect_to project_categories_url, notice: 'Project category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_category
      @project_category = ProjectCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_category_params
      params.require(:project_category).permit(:description, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

    @project = Project.find(params[:id])
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.project_categories.build
  end

  # GET /projects/1/edit
  def edit
    # binding.pry
    #@project = Project.new(project_params)
  end

  # POST /projects
  # POST /projects.json
  def create
     #binding.pry
    @project = Project.new(project_params)

     if @project.save
      redirect_to @project, notice: 'project was successfully created.'
    else
      render :new
    end

  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
      #binding.pry
      @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: 'Survey was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
      redirect_to projects_url, notice: 'Survey was successfully destroyed.'
  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :company, :location, :supervisior, :date, 
        :manday, :workingweek, :holiday, :user_id,
        project_categories_attributes: [:id,:description,:project_id,:_destroy, 
          {tasks_attributes:[:id,:_destroy,:description,:project_category_id,:startdate,:enddate,:toatalmandays]}]
        )
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :startdate, :enddate, :toatalmandays, :project_category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_categories_helper.rb
module ProjectCategoriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |questions_for_form|
      render(association.to_s.singularize + "_fields", f: questions_for_form)
    end
    link_to(name, '', class: "add_fields", data: { id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Caston42</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/project_categories/_form.html.erb
<%= form_for(@project_category) do |f| %>
  <% if @project_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_category.errors.count, "error") %> prohibited this project_category from being saved:</h2>

      <ul>
      <% @project_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_categories/edit.html.erb
<h1>Editing Project Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_category %> |
<%= link_to 'Back', project_categories_path %>

app/views/project_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Project Categories</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_categories.each do |project_category| %>
      <tr>
        <td><%= project_category.description %></td>
        <td><%= project_category.project %></td>
        <td><%= link_to 'Show', project_category %></td>
        <td><%= link_to 'Edit', edit_project_category_path(project_category) %></td>
        <td><%= link_to 'Destroy', project_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project category', new_project_category_path %>

app/views/project_categories/new.html.erb
<h1>New Project Category</h1>

<%= render 'form' %>

<%= link_to 'Back', project_categories_path %>

app/views/project_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @project_category.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @project_category.project %>
</p>

<%= link_to 'Edit', edit_project_category_path(@project_category) %> |
<%= link_to 'Back', project_categories_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :supervisior %><br>
    <%= f.text_field :supervisior %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :manday %><br>
    <%= f.number_field :manday %>
  </div>
  <div class="field">
    <%= f.label :workingweek %><br>
    <%= f.number_field :workingweek %>
  </div>
  <div class="field">
    <%= f.label :holiday %><br>
    <%= f.number_field :holiday %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
   <%= f.fields_for :project_categories do |cats_for_form| %>
    <%= render 'project_category_fields', f: cats_for_form %>
  <% end %>
  <%= link_to_add_fields "Add project category ", f, :project_categories %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project_category_fields.html.erb
<fieldset>
  <%= f.label :description, "Project Category" %>
  <%= f.text_field :description %>
  <%= f.label :project_id %>
   <%= f.text_field :project_id %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>

  <%= f.fields_for :tasks do |tasks_form| %>
    <%= render 'task_fields', f: tasks_form %>
  <% end %>
  <%= link_to_add_fields "Add tasks", f, :tasks %>
</fieldset>

app/views/projects/_task_fields.html.erb
<fieldset>
  <%= f.label :description, "Task" %>
  <%= f.text_area :description %>
  <%= f.label :startdate %>
  <%= f.datetime_select :startdate %>
  <%= f.label :enddate %>
  <%= f.datetime_select :enddate %>
  <%= f.label :toatalmandays %>
   <%= f.number_field :toatalmandays %>
   <%= f.label :project_category_id %>
   <%= f.text_field :project_category_id %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Company</th>
      <th>Location</th>
      <th>Supervisior</th>
      <th>Date</th>
      <th>Manday</th>
      <th>Workingweek</th>
      <th>Holiday</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.company %></td>
        <td><%= project.location %></td>
        <td><%= project.supervisior %></td>
        <td><%= project.date %></td>
        <td><%= project.manday %></td>
        <td><%= project.workingweek %></td>
        <td><%= project.holiday %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @project.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @project.location %>
</p>

<p>
  <strong>Supervisior:</strong>
  <%= @project.supervisior %>
</p>

<p>
  <strong>Date:</strong>
  <%= @project.date %>
</p>

<p>
  <strong>Manday:</strong>
  <%= @project.manday %>
</p>

<p>
  <strong>Workingweek:</strong>
  <%= @project.workingweek %>
</p>

<p>
  <strong>Holiday:</strong>
  <%= @project.holiday %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br>
    <%= f.datetime_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br>
    <%= f.datetime_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :toatalmandays %><br>
    <%= f.number_field :toatalmandays %>
  </div>
  <div class="field">
    <%= f.label :project_category_id %><br>
    <%= f.text_field :project_category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Toatalmandays</th>
      <th>Project category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.description %></td>
        <td><%= task.startdate %></td>
        <td><%= task.enddate %></td>
        <td><%= task.toatalmandays %></td>
        <td><%= task.project_category %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @task.startdate %>
</p>

<p>
  <strong>Enddate:</strong>
  <%= @task.enddate %>
</p>

<p>
  <strong>Toatalmandays:</strong>
  <%= @task.toatalmandays %>
</p>

<p>
  <strong>Project category:</strong>
  <%= @task.project_category %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>